on: push

name: Build and push
jobs:
  setupDocker:
    - name: Docker login
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      with:
        args: DOCKER_USERNAME DOCKER_PASSWORD

  setupGoogleCloud:
    name: Setup Google Cloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: Set Credential Helper for Docker
      uses: actions/gcloud/cli@master
      needs: setupDocker
      with:
        args: auth configure-docker --quiet


  buildImage:
    - name: Docker build
      uses: actions/docker/cli@86ff551d26008267bb89ac11198ba7f1d807b699
      needs: [setupDocker, setupGoogleCloud]
      with:
        args: "build -t preetamjinka/contrast-notes:latest -t gcr.io/infinitynorm-001/contrast:latest ."

  pushImages:
    - name: Push image to GCR
      uses: actions/gcloud/cli@master
      needs: buildImage
      with:
        entrypoint: sh
        args: -c "docker push gcr.io/infinitynorm-001/contrast"
    - name: Push image to Docker Hub
      uses: actions/docker/cli@86ff551d26008267bb89ac11198ba7f1d807b699
      needs: buildImage
      with:
        args: push preetamjinka/contrast-notes:latest

  deploy:
    - name: Deploy Cloud Run Service
      uses: actions/gcloud/cli@master
      needs: pushImages
      with:
        entrypoint: sh
        args: -c "gcloud components install beta && gcloud components update && gcloud --quiet --project infinitynorm-001 beta run deploy contrast --image gcr.io/infinitynorm-001/contrast:latest --platform managed --region us-central1 --memory 128Mi"
